if(ENABLE_PLATFORM_STM32F1)
    set(PLATFORM_CFG_FULL_NAME "stm32_f1_03_c8")
    set(CORTEX_ARCHITECTURE "__ARM_ARCH_7M__")
else()
    set(PLATFORM_CFG_FULL_NAME "stm32_f4_11_re")
    set(CORTEX_ARCHITECTURE "__ARM_ARCH_7M__")
endif()

string(REPLACE "_" ";" PLATFORM_PARTS "${PLATFORM_CFG_FULL_NAME}")
list(GET PLATFORM_PARTS 0 PLATFORM_FAMILY)
list(GET PLATFORM_PARTS 1 PLATFORM_SERIES)
list(GET PLATFORM_PARTS 2 PLATFORM_SPECIFIC_FEATURES)
list(GET PLATFORM_PARTS 3 PLATFORM_PACKAGE_AND_FLASH)

# stm32f411re / stm32f103c8
string(REPLACE "_" "" PLATFORM_FULL_NAME_LOWER_CASE ${PLATFORM_CFG_FULL_NAME})

# STM32F411RE / STM32F103C8
string(TOUPPER ${PLATFORM_FULL_NAME_LOWER_CASE} PLATFORM_FULL_NAME_UPPER_CASE)

# stm32f4 / stm32f1
set(PLATFORM_LOWER_CASE "${PLATFORM_FAMILY}${PLATFORM_SERIES}")

# STM32F4 / STM32F1
string(TOUPPER ${PLATFORM_LOWER_CASE} PLATFORM_UPPER_CASE)

# stm32/f4 / stm32/f1
set(PLATFORM_FOLDER_LOWER_CASE "${PLATFORM_FAMILY}/${PLATFORM_SERIES}")

# STM32/F4 / STM32/F1
string(TOUPPER ${PLATFORM_FOLDER_LOWER_CASE} PLATFORM_FOLDER_UPPER_CASE)

# stm32f411 / stm32f103
set(PLATFORM_NO_PACKAGE_LOWER_CASE "${PLATFORM_LOWER_CASE}${PLATFORM_SPECIFIC_FEATURES}")

# STM32F411 / STM32F103
string(TOUPPER ${PLATFORM_NO_PACKAGE_LOWER_CASE} PLATFORM_NO_PACKAGE_UPPER_CASE)
